In [1]:
import numpy as np

In [99]:
# 3.1: 1D NumPy Arrays
mylist = [20,27,9,12,31,17,3,50,39,35]
arr = np.array(mylist)
print(arr*4)
print(np.mean(arr))
print(np.median(arr))
print(np.std(arr))
print(np.argmin(arr))
print(np.argmax(arr))
print(arr[6])
print(arr[7])
print(np.min(arr))
print(np.max(arr))
# yes, they match!
greater_than_20 = arr[arr>20]
print(greater_than_20)

[ 80 108  36  48 124  68  12 200 156 140]
24.3
23.5
13.97891269019161
6
7
3
50
3
50
[27 31 50 39 35]


In [58]:
# 3.2: 2D NumPy Arrays
matrix = np.array([
    [5,12,17,9],
    [8,21,14,3],
    [6,13,19,11]
])
print(matrix.shape) # 3 rows, 4 columns
print(matrix[:,2])
print(matrix[1,:])
print(matrix*2)
print(np.mean(matrix[:,0]))
print(np.mean(matrix[:,1]))
print(np.mean(matrix[:,2]))
print(np.mean(matrix[:,3]))
print(np.mean(matrix))
print(np.max(matrix[0]),np.max(matrix[1]),np.max(matrix[2]))
print(np.min(matrix[:,0]),np.min(matrix[:,1]),np.min(matrix[:,2]),np.min(matrix[:,3]))
flat_matrix = matrix.flatten()
print(flat_matrix) # converts to a 1D matrix
print(np.argmin(flat_matrix),np.argmax(flat_matrix))
print(np.unravel_index(7, (3,4))) # minimum value is at [1,3] in real matrix
print(np.unravel_index(5, (3,4))) # maximum value is at [1,1] in real matrix
greater_than_15 = matrix[matrix>15]
print(greater_than_15)
print(np.sort(matrix, axis=0)) # sorted along columns
print(np.sort(matrix, axis=1)) # sorted along rows

(3, 4)
[17 14 19]
[ 8 21 14  3]
[[10 24 34 18]
 [16 42 28  6]
 [12 26 38 22]]
6.333333333333333
15.333333333333334
16.666666666666668
7.666666666666667
11.5
17 21 19
5 12 14 3
[ 5 12 17  9  8 21 14  3  6 13 19 11]
7 5
(np.int64(1), np.int64(3))
(np.int64(1), np.int64(1))
[17 21 19]
[[ 5 12 14  3]
 [ 6 13 17  9]
 [ 8 21 19 11]]
[[ 5  9 12 17]
 [ 3  8 14 21]
 [ 6 11 13 19]]


In [67]:
# 4. Prime Star Systems
arr = np.array([
    [2,3,5],
    [14,6,8],
    [11,13,17],
    [7,10,13]
])
def is_it_prime(n): # checks for prime numbers
    if n<2: 
        return False # for the 1 and 0 nonsense
    for i in range(2,int(n**0.5)+1): # no factors past square root
        if n%i ==0:
            return False
    return True
print(is_it_prime(11)) #checking if it works, yippee it does
def prime_rows(array):
    result = []
    for row in array:
        has_prime = False
        for x in row:
            if is_it_prime(x):
                has_prime = True
            if has_prime:
                result.append(row)
                break # to prevent it from looping through every element in the row. and giving me a triple response
    return np.array(result)
print(prime_rows(arr))

True
[[ 2  3  5]
 [11 13 17]
 [ 7 10 13]]


In [80]:
# 5. Let's Play Checkers!
board = np.zeros((8,8))
print(board)
def checkerboard():
    board = np.zeros((8,8))
    board[0::2,0::2] = 1
    board[1::2,1::2] = 1
    return board
print(checkerboard())
def reversed_checkerboard():
    board = checkerboard()
    return 1-board
print(reversed_checkerboard())

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]
[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]
[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [104]:
# 6. The Expanding Universe
def expansion(arr,n):
    return np.array([" ".join(c+" "*n for c in s)[:-n] for s in arr])
universe = np.array(["galaxy", "cluster"])
print(expansion(universe,2))

['g   a   l   a   x   y' 'c   l   u   s   t   e   r']


In [110]:
# 7. Second-Brightest Star
def second_brightest(arr):
    sorted_rows = np.sort(arr,axis=1)
    second_largest = sorted_rows[:,-2]
    return second_largest
np.random.seed(123)
stars = np.random.randint(500,2000,(5,5))
print(stars)
print(second_brightest(stars))

[[1889 1906 1846 1622 1541]
 [ 606 1647 1738  596  613]
 [1138  547  573 1442  724]
 [ 611 1933 1863 1346 1777]
 [ 920 1108 1732 1592  951]]
[1889 1647 1138 1863 1592]
